[book]
authors = ["Claudio"]
language = "it"
multilingual = false
src = "src"
title = "Educazione civica - Sostenibilità di Internet"

[build]
create-missing = false

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/wbigger/book-sustainability"